test(reusable-workflows): 🧪 fixed git push, run overall test

diff --git a/.github/workflows/cert-renewal.yaml b/.github/workflows/cert-renewal.yaml
--- a/.github/workflows/cert-renewal.yaml
+++ b/.github/workflows/cert-renewal.yaml
@@ -96,31 +96,31 @@ jobs:
           EOF
           cat input.tfvars
 
-          # terraform init
-          # terraform plan -var-file=input.tfvars -input=false
-          # terraform apply -auto-approve -var-file=input.tfvars -input=false
-          # ## get the instance public ip
-          # INSTANCE_PUBLIC_IP=$(terraform output -raw auto-letsencrypt-instance-public-ip)
-          # echo $INSTANCE_PUBLIC_IP
-          # ## check if the cert is ready
-          # time=0
-          # while [ "$(ssh -oStrictHostKeyChecking=no -i $GITHUB_WORKSPACE/ssh_private_key ubuntu@$INSTANCE_PUBLIC_IP "cloud-init status")" != "status: done" ]
-          # do
-          #   sleep 60
-          #   time=$((time+60))
-          #   echo "INFO :: Waiting for SSL certs to be generated. Time elapsed: ${time} seconds"
-          #   if [ ${time} -gt 900 ]; then
-          #     echo "ERROR :: Timeout waiting for SSL certs to be generated on $INSTANCE_PUBLIC_IP"
-          #     ssh -oStrictHostKeyChecking=no -i $GITHUB_WORKSPACE/ssh_private_key ubuntu@$INSTANCE_PUBLIC_IP "cat /var/log/cloud-init-output.log"
-          #     exit 1
-          #   fi
-          # done
-          # ## get the generated cert
-          # scp -oStrictHostKeyChecking=no -i $GITHUB_WORKSPACE/ssh_private_key \
-          #   ubuntu@$INSTANCE_PUBLIC_IP:/manual-letsencrypt/letsencrypt/letsencrypt-keys/live/${{inputs.ROUTE53_RECORD_NAME}}.${{inputs.ROUTE53_ZONE_NAME}}/"{fullchain.pem,privkey.pem}" \
-          #   $GITHUB_WORKSPACE/caller-repo/${{inputs.CALLER_REPO_SUBPATH_FOR_CERT}}
-          # ls -lah $GITHUB_WORKSPACE/caller-repo/${{inputs.CALLER_REPO_SUBPATH_FOR_CERT}}
-          # terraform destroy -auto-approve -var-file=input.tfvars -input=false
+          terraform init
+          terraform plan -var-file=input.tfvars -input=false
+          terraform apply -auto-approve -var-file=input.tfvars -input=false
+          ## get the instance public ip
+          INSTANCE_PUBLIC_IP=$(terraform output -raw auto-letsencrypt-instance-public-ip)
+          echo $INSTANCE_PUBLIC_IP
+          ## check if the cert is ready
+          time=0
+          while [ "$(ssh -oStrictHostKeyChecking=no -i $GITHUB_WORKSPACE/ssh_private_key ubuntu@$INSTANCE_PUBLIC_IP "cloud-init status")" != "status: done" ]
+          do
+            sleep 60
+            time=$((time+60))
+            echo "INFO :: Waiting for SSL certs to be generated. Time elapsed: ${time} seconds"
+            if [ ${time} -gt 900 ]; then
+              echo "ERROR :: Timeout waiting for SSL certs to be generated on $INSTANCE_PUBLIC_IP"
+              ssh -oStrictHostKeyChecking=no -i $GITHUB_WORKSPACE/ssh_private_key ubuntu@$INSTANCE_PUBLIC_IP "cat /var/log/cloud-init-output.log"
+              exit 1
+            fi
+          done
+          ## get the generated cert
+          scp -oStrictHostKeyChecking=no -i $GITHUB_WORKSPACE/ssh_private_key \
+            ubuntu@$INSTANCE_PUBLIC_IP:/manual-letsencrypt/letsencrypt/letsencrypt-keys/live/${{inputs.ROUTE53_RECORD_NAME}}.${{inputs.ROUTE53_ZONE_NAME}}/"{fullchain.pem,privkey.pem}" \
+            $GITHUB_WORKSPACE/caller-repo/${{inputs.CALLER_REPO_SUBPATH_FOR_CERT}}
+          ls -lah $GITHUB_WORKSPACE/caller-repo/${{inputs.CALLER_REPO_SUBPATH_FOR_CERT}}
+          terraform destroy -auto-approve -var-file=input.tfvars -input=false
 
           cd $GITHUB_WORKSPACE/caller-repo
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
